# Model Configurations
goal_dim: 32
horizon: 32
max_interval: 32
n_critics: 4
rl_coeff: 2.5
kl_coeff: 0
decoder_coeff: 0
diffuser_coeff: 0.001
predict_epsilon: True
diffuser_timesteps: 200
returns_condition: False
goal_condition: True
condition_guidance_w: 0.
hidden_size: 512

# Training Configurations
batch_size: 32
learning_rate: 0.0002
warmup_updates: 50000
updates_per_epoch: 10000
epochs: 150

# Evaluation Configurations
threshold: 0.1
timelimit: 100